# Generated by Django 4.2.5 on 2023-09-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_chooseproduct_qr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chooseproduct",
            name="qr",
            field=models.ImageField(blank=True, upload_to="media"),
        ),
    ]
