# Generated by Django 4.2.5 on 2023-09-13 16:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_alter_chooseproduct_qr"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChooseProduct",
        ),
    ]
