# Generated by Django 4.2.5 on 2023-09-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_delete_chooseproduct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=250, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=250, unique=True, verbose_name="slug"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=250, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(max_length=250, unique=True, verbose_name="slug"),
        ),
    ]
