# Generated by Django 4.2.5 on 2023-09-23 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0008_productreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="productreview",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productreview",
            name="review",
            field=models.IntegerField(
                blank=True,
                default=5,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
