# Generated by Django 4.2.5 on 2023-09-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer_service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "customer_service_rep",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "customer_phone",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "customer_email",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "customer_title",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("customer_description", models.TextField(blank=True, null=True)),
                ("ticket_date", models.DateTimeField(auto_now_add=True)),
                ("ticket_status", models.BooleanField(default=False)),
                ("order_number", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Customer Service",
                "verbose_name_plural": "Customer Services",
                "db_table": "customer_service",
                "ordering": ["-ticket_date"],
            },
        ),
    ]
