# Generated by Django 4.2.5 on 2023-09-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer_service",
            name="ticket_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
