# Generated by Django 4.2.5 on 2023-09-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_service", "0002_customer_service_ticket_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer_service",
            name="category",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
