# Generated by Django 4.2.5 on 2023-09-20 23:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_service", "0003_customer_service_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer_service",
            name="ticket_number",
        ),
    ]
