# Generated by Django 4.2.5 on 2023-09-20 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_service", "0004_remove_customer_service_ticket_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer_service",
            name="order_number",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
