# Generated by Django 4.2.5 on 2023-09-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_service", "0005_alter_customer_service_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer_service",
            name="ticket_status",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
