# Generated by Django 4.2.5 on 2023-09-12 19:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0003_remove_cartitem_kids_name_remove_cartitem_qr"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="parent",
        ),
    ]
