# Generated by Django 4.2.5 on 2023-09-13 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_alter_generateqr_type"),
        ("cart", "0004_remove_cartitem_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="kids_name",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="parent",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="home.generateqr",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="qr",
            field=models.ImageField(blank=True, null=True, upload_to="media"),
        ),
    ]
