# Generated by Django 4.2.5 on 2023-09-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0007_alter_cartitem_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
