# Generated by Django 4.2.5 on 2023-09-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_alter_generateqr_qr"),
    ]

    operations = [
        migrations.AddField(
            model_name="generateqr",
            name="type",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
