# Generated by Django 4.2.5 on 2023-09-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_alter_generateqr_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generateqr",
            name="address",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="address"
            ),
        ),
        migrations.AlterField(
            model_name="generateqr",
            name="name",
            field=models.CharField(max_length=300, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="generateqr",
            name="phoneNumber",
            field=models.CharField(max_length=300, verbose_name="phoneNumber"),
        ),
        migrations.AlterField(
            model_name="generateqr",
            name="qr",
            field=models.ImageField(blank=True, upload_to="media", verbose_name="qr"),
        ),
        migrations.AlterField(
            model_name="generateqr",
            name="summary",
            field=models.TextField(blank=True, null=True, verbose_name="summary"),
        ),
        migrations.AlterField(
            model_name="generateqr",
            name="type",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="type"
            ),
        ),
    ]
