# Generated by Django 4.2.5 on 2023-09-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_alter_generateqr_qr"),
    ]

    operations = [
        migrations.AddField(
            model_name="generateqr",
            name="vistor_city",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="vistor_city"
            ),
        ),
        migrations.AddField(
            model_name="generateqr",
            name="vistor_country_name",
            field=models.CharField(
                blank=True,
                max_length=300,
                null=True,
                verbose_name="vistor_country_name",
            ),
        ),
        migrations.AddField(
            model_name="generateqr",
            name="vistor_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="generateqr",
            name="vistor_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=20, null=True
            ),
        ),
    ]
