# Generated by Django 4.2.5 on 2023-09-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_remove_generateqr_vistor_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generateqr",
            name="vistor_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="generateqr",
            name="vistor_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
