# Generated by Django 4.2.5 on 2023-09-12 19:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="kids",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="parent",
        ),
    ]
