# Generated by Django 4.2.5 on 2023-09-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0004_alter_orderitem_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="ready_to_ship",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="ship",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
