# Generated by Django 4.2.5 on 2023-09-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0005_orderitem_ready_to_ship_orderitem_ship"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="ready_to_ship",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="ship",
        ),
        migrations.AddField(
            model_name="order",
            name="ready_to_ship",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="ship",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
