# Generated by Django 4.2.5 on 2023-09-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0006_remove_orderitem_ready_to_ship_remove_orderitem_ship_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="billingAddress1",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="billingAddress1"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="billingCity",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="billingCity"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="billingCountry",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="billingCountry"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="billingName",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="billingName"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="billingPostcode",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="billingPostcode"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shippingAddress1",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="shippingAddress1"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shippingCity",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="shippingCity"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shippingCountry",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="shippingCountry"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shippingName",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="shippingName"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shippingPostcode",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="shippingPostcode"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="token",
            field=models.CharField(blank=True, max_length=250, verbose_name="token"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="kids_name",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="kids_name"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.CharField(max_length=250, verbose_name="product"),
        ),
    ]
