# Generated by Django 4.2.5 on 2023-09-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0007_alter_order_billingaddress1_alter_order_billingcity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="token",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
